services:
  main-db:
    image: postgres:16.1
    container_name: main_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  stats-db:
    image: postgres:16.1
    container_name: stats_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: statDB
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser"]
      interval: 5s
      retries: 5

  stats-server:
    image: alpine:latest
    container_name: stats_server
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    depends_on:
      - stats-db
    ports:
      - "9090:9090"

  ewm-service:
    image: alpine:latest
    container_name: ewm_service
    command: ["sh", "-c", "while true; do sleep 3600; done"]